services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  app:
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm run test
    volumes:
      - "./app:/app"
    image: craz3r/devops-for-programmers-project-74