services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
  caddy:
    image: caddy:2.6.3
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"